modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="myfirstmod"
version="1.0.0"
displayName="MyFirstMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Phizilion, MCreator"

[[dependencies.myfirstmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



